Feature: As a User, I should be able to create and maintain a profile page that is visible to other users.
  Scenario Outline: As a user, I should be able to update my profile picture.
    Given I am on the login page
    When  I enter my username <username>
    When  I type my password <password>
    When  I click the login button
    When  I click the profile picture <picture>
    Then  I am on the profile page
    When  I click the edit profile button
    When  I enter my personal <about_me> incorrectly
    When  I type my birthday <birthday>
    When  I click the save changes button
    When  I click the close button
    When  I click on my follower
    Then  I am on their profile

    Examples:
      | username | password | picture             | about_me                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | birthday |
      | username | password | downloads/Husky.jpg | I am a person                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |          |
      | username | password | downloads/Husky.jpg | thisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylongthisaboutmesectioniswaywaywaywaywaywaywaytoolongtopassthroughthecharactercheckingtestsoIwillmakeitextremelylong | 01011997 |
      | username | password | downloads/Husky.jpg | I am a person                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 01011997 |
